services:
    ProfitabilityCalculator:
        class: DomainBundle\Exchange\Policy\ProfitabilityCalculator
        arguments:
          - '@ORM\UserExchangeAccountTransactionRepository'
    ProfileData:
        class: DomainBundle\Exchange\Policy\ProfileData
        arguments:
          - '@ORM\UserExchangeAccountRepository'
          - '@ORM\UserExchangeAccountTransactionRepository'
    DomainCurrenciesPolicy:
        class: Domain\Policy\DomainCurrenciesPolicy
    BalanceHistory:
        class: DomainBundle\Exchange\Policy\BalanceHistory
        arguments:
          - '@doctrine'
          - '@DomainCurrenciesPolicy'
