services:
    ProfitabilityCalculator:
        class: DomainBundle\Exchange\Policy\ProfitabilityCalculator
        arguments:
          - '@ORM\UserAccountTransactionRepository'
          - '@AnyMomentUserBalanceResolver'
    DomainCurrenciesPolicy:
        class: Domain\Policy\DomainCurrenciesPolicy

    AdminBalanceHistory:
        class: DomainBundle\Exchange\Policy\BalanceHistory
        arguments:
          - '@doctrine'
          - '@AdminMoneyFormatter'

    PublicBalanceHistory:
        class: DomainBundle\Exchange\Policy\BalanceHistory
        arguments:
          - '@doctrine'
          - '@PublicMoneyFormatter'

    AnyMomentUserBalanceResolver:
        class: DomainBundle\Exchange\Policy\AnyMomentUserBalanceResolver
        arguments:
          - '@ORM\UserAccountTransactionRepository'
