services:
    TradingStrategyRepository:
        class: DomainBundle\Exchange\Repository\TradingStrategyRepository
        arguments:
            $strategies:
                - '@TradingStrategy\Martin'
