imports:
    - { resource: '@DomainBundle/Resources/config/usecases.yml' }
    - { resource: '@DomainBundle/Resources/config/exchanges.yml' }
    - { resource: '@DomainBundle/Resources/config/strategies.yml' }
    - { resource: '@DomainBundle/Resources/config/repositories.yml' }
    - { resource: '@DomainBundle/Resources/config/orm_repositories.yml' }

services:
    TwigExtension:
        class: DomainBundle\TwigExtension
        arguments: ['@service_container']
        tags:
            - { name: twig.extension }
    Exchange\IdFactory:
        class: DomainBundle\Exchange\Factory\IdFactory
        arguments: ['@doctrine.dbal.default_connection']
    UserIdFactory:
        class: DomainBundle\Factory\UserIdFactory
        arguments: ['@doctrine.dbal.default_connection']