imports:
    - { resource: '@DomainBundle/Resources/config/exchanges.yml' }
    - { resource: '@DomainBundle/Resources/config/strategies.yml' }
    - { resource: '@DomainBundle/Resources/config/repositories.yml' }
    - { resource: '@DomainBundle/Resources/config/orm_repositories.yml' }

services:
    Exchange\IdFactory:
        class: DomainBundle\Exchange\Factory\IdFactory
        arguments:
            - '@doctrine.dbal.default_connection'