services:
    TradingStrategy\Martin:
        class: DomainBundle\Exchange\TradingStrategy\Martin
        arguments: ['@ORM\BotTradingSessionRepository','@ORM\BotTradingSessionAccountRepository', '@UseCase\GetBotTradingSessionAccountUseCase']