services:
    TradingStrategy\Martin:
        class: DomainBundle\Exchange\TradingStrategy\Martin
        arguments: ['@ORM\BotTradingSessionRepository', '@ORM\BotTradingSessionAccountRepository', '@UseCase\GetBotTradingSessionBalancesUseCase', '@ORM\BotRepository', '@ExchangeRepository', '@UseCase\CreateOrderUseCase', '@ORM\OrderRepository', '@UseCase\CancelOrderUseCase', '@logger']
    TradingStrategy\EmaWithMartin:
        class: DomainBundle\Exchange\TradingStrategy\EmaWithMartin
        arguments: ['@ORM\BotTradingSessionRepository', '@ORM\BotTradingSessionAccountRepository', '@UseCase\GetBotTradingSessionBalancesUseCase', '@ORM\BotRepository', '@ExchangeRepository', '@UseCase\CreateOrderUseCase', '@ORM\OrderRepository', '@UseCase\CancelOrderUseCase', '@monolog.logger.security', '@TradingStrategy\Martin']