services:
    UseCase\CreateUserUseCase:
        class: Domain\UseCase\CreateUserUseCase
        arguments: ['@UserIdFactory', '@ORM\UserRepository']
    UseCase\CreateBotUseCase:
        class: Domain\Exchange\UseCase\CreateBotUseCase
        arguments: ['@Exchange\IdFactory', '@ExchangeRepository', '@TradingStrategyRepository', '@ORM\BotRepository']
    UseCase\EditBotUseCase:
        class: Domain\Exchange\UseCase\EditBotUseCase
        arguments: ['@Exchange\IdFactory', '@ExchangeRepository', '@TradingStrategyRepository', '@ORM\BotRepository']
    UseCase\GetBotExchangeAccountUseCase:
        class: Domain\Exchange\UseCase\GetBotExchangeAccountUseCase
        arguments: ['@ORM\BotExchangeAccountRepository']
    UseCase\GetUserExchangeAccountUseCase:
        class: Domain\Exchange\UseCase\GetUserExchangeAccountUseCase
        arguments: ['@ORM\UserExchangeAccountRepository']
    UseCase\GetBotTradingSessionAccountUseCase:
        class: Domain\Exchange\UseCase\GetBotTradingSessionAccountUseCase
        arguments: ['@ORM\BotTradingSessionAccountRepository']
    UseCase\UserDepositMoneyUseCase:
        class: Domain\Exchange\UseCase\UserDepositMoneyUseCase
        arguments: ['@ORM\UserRepository', '@ExchangeRepository', '@ORM\UserExchangeAccountRepository', '@Exchange\IdFactory', '@ORM\BotExchangeAccountRepository', '@ORM\UserExchangeAccountTransactionRepository', '@ORM\BotExchangeAccountTransactionRepository', '@ORM\BotRepository', '@UseCase\GetBotExchangeAccountUseCase', '@UseCase\GetUserExchangeAccountUseCase']
    UseCase\ProcessBotTradingUseCase:
        class: Domain\Exchange\UseCase\ProcessBotTradingUseCase
        arguments: ['@ORM\BotTradingSessionRepository', '@Exchange\IdFactory', '@TradingStrategyRepository', '@ORM\BotExchangeAccountRepository', '@ORM\BotExchangeAccountTransactionRepository', '@ORM\BotTradingSessionAccountRepository', '@ORM\BotTradingSessionAccountTransactionRepository', '@ORM\BotRepository', '@ORM\UserExchangeAccountRepository', '@ORM\UserExchangeAccountTransactionRepository', '@UseCase\GetBotExchangeAccountUseCase']
    UseCase\CreateOrderUseCase:
        class: Domain\Exchange\UseCase\CreateOrderUseCase
        arguments: ['@ExchangeRepository', '@ORM\BotTradingSessionAccountRepository', '@ORM\BotTradingSessionAccountTransactionRepository', '@UseCase\GetBotTradingSessionBalancesUseCase', '@Exchange\IdFactory', '@ORM\OrderRepository']
    UseCase\GetBotTradingSessionBalancesUseCase:
        class: Domain\Exchange\UseCase\GetBotTradingSessionBalancesUseCase
        arguments: ['@UseCase\GetBotTradingSessionAccountUseCase', '@ORM\OrderRepository', '@ExchangeRepository', '@ORM\BotTradingSessionRepository']
    UseCase\SyncExchangeUseCase:
        class: Domain\Exchange\UseCase\SyncExchangeUseCase
        arguments: ['@ORM\OrderRepository', '@ExchangeRepository']
    UseCase\UpdateOrderUseCase:
        class: Domain\Exchange\UseCase\UpdateOrderUseCase
        arguments: ['@ORM\OrderRepository', '@ORM\BotTradingSessionRepository', '@ExchangeRepository', '@UseCase\GetBotTradingSessionAccountUseCase', '@ORM\BotTradingSessionAccountRepository', '@ORM\BotTradingSessionAccountTransactionRepository', '@Exchange\IdFactory']