services:
    UseCase\CreateBotUseCase:
        class: Domain\Exchange\UseCase\CreateBotUseCase
        arguments: ['@Exchange\IdFactory', '@ExchangeRepository', '@TradingStrategyRepository', '@ORM\BotRepository']