version: '2'

services:
  app:
    container_name: criptim.app
    build: ./docker/php
    depends_on:
      - postgres
      - memcached
    volumes:
      - .:/criptim
    # dns:
      # - 172.18.45.11
      # - 172.18.45.12

  nginx:
    container_name: criptim.nginx
    image: nginx:latest
    volumes_from:
      - app
    volumes:
      - ./docker/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites-enabled:/etc/nginx/sites-enabled
    ports:
      - "80:80"
  postgres:
    container_name: criptim.postgres
    image: postgres:9.5-alpine
    ports:
      - "6432:5432"
    environment:
      POSTGRES_PASSWORD: dev
      POSTGRES_USER: dev
      POSTGRES_DB: criptim
      TZ: Europe/Moscow

  memcached:
    container_name: criptim.memcached
    image: memcached
    ports:
      - "11211:11211"

  node:
    container_name: criptim.node
    image: node:6.12.0
    volumes:
      - .:/criptim