Domain\Entity\User:
    type: entity
    table: domain_user
    repositoryClass: DomainBundle\Repository\UserRepository
    id:
        id:
            type: userId
            generator: { strategy: NONE }
            sequenceGenerator:
                sequenceName: user_id_seq