Domain\Entity\UserAccount:
    repositoryClass: DomainBundle\Repository\UserAccountRepository
    type: entity
    id:
        userId:
            type: userId
        currency:
            type: currency
    fields:
        balance:
            type: money
