# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value
    web_dir:  '%kernel.project_dir%/web/'
services:
    entry_point.user_login:
        class: AppBundle\LoginEntryPoint
        arguments:
            - '@router'
            - '%kernel.app_type%.auth.login'

    app.event_listner.after_registration_listener:
        class: AppBundle\EventListener\AfterRegistrationListener
        arguments: ['@router', '%kernel.app_type%.index']
        tags:
            - { name: kernel.event_subscriber }

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    app.cache:
        class: Symfony\Component\Cache\Adapter\TagAwareAdapter
        arguments: [ '@app.cache.data.adapter', '@app.cache.tags.adapter' ]