Domain\Exchange\Entity\Bot:
    type: entity
    id:
        id:
            type: botId
            generator: { strategy: SEQUENCE }
            sequenceGenerator:
                sequenceName: bot_id_seq
    fields:
        exchangeId:
            type: exchangeId
        tradingStrategyId:
            type: tradingStrategyId
        tradingStrategySettings:
            type: tradingStrategySettings
        status:
            type: string