Domain\Exchange\Entity\BotExchangeAccountTransaction:
    repositoryClass: DomainBundle\Exchange\Repository\BotExchangeAccountTransactionRepository
    type: entity
    id:
        id:
            type: botExchangeAccountTransactionId
            generator: { strategy: NONE }
            sequenceGenerator:
                sequenceName: bot_exchange_account_transaction_id_seq
    fields:
        botId:
            type: botId
        exchangeId:
            type: exchangeId
        currency:
            type: currency
        money:
            type: money
        balance:
            type: money
        type:
            type: string
        dt:
            type: dateTimeImmutable
