Domain\Exchange\Entity\BotTradingSessionAccountTransaction:
    type: entity
    id:
        id:
            type: botTradingSessionAccountTransactionId
            generator: { strategy: SEQUENCE }
            sequenceGenerator:
                sequenceName: bot_trading_session_account_transaction_id_seq
    fields:
        botTradingSessionId:
            type: botTradingSessionId
        currency:
            type: currency
        money:
            type: money
        balance:
            type: money
        type:
            type: string
        dt:
            type: dateTimeImmutable
