Domain\Exchange\Entity\BotTradingSession:
    repositoryClass: DomainBundle\Exchange\Repository\BotTradingSessionRepository
    type: entity
    id:
        id:
            type: botTradingSessionId
            generator: { strategy: NONE }
            sequenceGenerator:
                sequenceName: bot_trading_session_id_seq
    fields:
        botId:
            type: botId
        tradingStrategyId:
            type: tradingStrategyId
        tradingStrategySettings:
            type: tradingStrategySettings
        status:
            type: string
        createdAt:
            type: dateTimeImmutable
        updatedAt:
            type: dateTimeImmutable
        endedAt:
            type: dateTimeImmutable
            nullable: true