criptim:
    resource: '@CriptimBundle/Controller/'
    type: annotation

fos_user_security_logout:
    path:     /logout
    defaults: { _controller: FOSUserBundle:Security:logout }

fos_user_resetting_request:
    path:     /restore
    defaults: { _controller: FOSUserBundle:Resetting:request }

fos_user_resetting_send_email:
    path:     /restore/send
    defaults: { _controller: FOSUserBundle:Resetting:sendEmail }

fos_user_resetting_check_email:
    path:     /restore/check
    defaults: { _controller: FOSUserBundle:Resetting:checkEmail }

fos_user_resetting_reset:
    path:     /restore/{token}
    defaults: { _controller: FOSUserBundle:Resetting:reset }

fos_user_security_check:
    path:     /login_check
    defaults: { _controller: FOSUserBundle:Security:check }
