<?php
/**
 * Created by PhpStorm.
 * User: mix6s
 * Date: 10.01.18
 * Time: 22:03
 */

namespace Domain\Tests\UseCase\TransferInvestorBitMoneyFromMainToTradingAccount;


use Domain\Tests\UseCaseTestCase;

class HandlerTest extends UseCaseTestCase
{
    /** @var  Container */
    private $container;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->container = new Container();
    }
}